<a href="https://colab.research.google.com/github/onegi95/TIL/blob/master/lab06_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x_data = [[1,2,1,1],
          [2,1,3,2],
          [3,1,3,4],
          [4,1,5,5,],
          [1,7,5,5],
          [1,2,5,6],
          [1,6,6,6],
          [1,7,7,7]]

y_data = [[0,0,1],
          [0,0,1],
          [0,0,1],
          [0,1,0],
          [0,1,0],
          [0,1,0],
          [1,0,0],
          [1,0,0],]

In [4]:
import numpy as np

# conver t into numpy and float format
x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

In [5]:
nb_classes = 3 #num classes

In [12]:
import tensorflow as tf

W = tf.Variable(tf.random.normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random.normal([nb_classes]), name='bias')
# logistic classifier



tf.Tensor(
[[ 1.5807766   2.098824   -2.3775187 ]
 [ 1.0915214  -0.7006056  -1.6607829 ]
 [ 3.249484   -2.031421   -0.41470528]
 [ 3.147521   -3.348388   -0.7863033 ]
 [ 7.8267665   6.1532426  -7.7148566 ]
 [ 7.3618684  -1.8233359  -1.7165753 ]
 [ 8.516856    3.8313057  -6.6004405 ]
 [ 9.981531    4.474295   -7.662692  ]], shape=(8, 3), dtype=float32)
tf.Tensor(
[[3.70666564e-01 6.22255266e-01 7.07811583e-03]
 [8.12752903e-01 1.35409057e-01 5.18379696e-02]
 [9.70202327e-01 4.93622012e-03 2.48613730e-02]
 [9.79356885e-01 1.47843990e-03 1.91647336e-02]
 [8.42045009e-01 1.57954901e-01 1.49862913e-07]
 [9.99783456e-01 1.02523241e-04 1.14074355e-04]
 [9.90856528e-01 9.14327893e-03 2.69558143e-07]
 [9.95959103e-01 4.04091133e-03 2.16497629e-08]], shape=(8, 3), dtype=float32)


In [10]:
# softmax onehot test

sample_db = [[8,2,1,4]]
smaple_db = np.asarray(sample_db, dtype=np.float32)
softmax = tf.nn.softmax([-1, 0., 1.])


tf.Tensor([0.09003057 0.24472848 0.66524094], shape=(3,), dtype=float32)


In [23]:
# cost function : cross entropy

# cross entropy cost/loss
def cost_fn(X, Y):
  logits = hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
  cost = -tf.reduce_sum(Y*tf.math.log(logits), axis=1)
  cost_mean = tf.reduce_mean(cost)
  return cost_mean
print(cost_fn(x_data, y_data))

tf.Tensor(0.16325289, shape=(), dtype=float32)


In [18]:
def grad_fn(X, Y):
  with tf.GradientTape() as tape:
    cost = cost_fn(X, Y)
    grads = tape.gradient(cost, [W,b]) # [W,b] = variables
    return grads
print(grad_fn(x_data, y_data))

tf.Tensor(
[4.9507475e+00 2.9596324e+00 3.6944399e+00 6.5167680e+00 1.8454458e+00
 9.1854210e+00 9.1855302e-03 4.0490832e-03], shape=(8,), dtype=float32)
[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.3316064 , -0.61437035, -0.71723604],
       [ 1.4142975 , -0.92807883, -0.48621857],
       [ 2.467789  , -1.6344856 , -0.8333034 ],
       [ 2.612443  , -1.7757818 , -0.8366612 ]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.62020284, -0.25808492, -0.36211792], dtype=float32)>]


In [21]:
def fit(X, Y, epochs=2000, verbose=100):
  optimizer = tf.optimizers.SGD(learning_rate=0.1)
  for i in range(epochs):
    grads = grad_fn(X, Y)
    optimizer.apply_gradients(zip(grads, [W,b]))
    if (i == 0) | ((i+1)%verbose==0):
      print('Loss at epoch %d: %f' %(i+1, cost_fn(X,Y).numpy()))

In [24]:
fit(x_data, y_data)

Loss at epoch 1: 0.163193
Loss at epoch 100: 0.157497
Loss at epoch 200: 0.152118
Loss at epoch 300: 0.147081
Loss at epoch 400: 0.142354
Loss at epoch 500: 0.137911
Loss at epoch 600: 0.133727
Loss at epoch 700: 0.129782
Loss at epoch 800: 0.126055
Loss at epoch 900: 0.122529
Loss at epoch 1000: 0.119189
Loss at epoch 1100: 0.116021
Loss at epoch 1200: 0.113011
Loss at epoch 1300: 0.110150
Loss at epoch 1400: 0.107425
Loss at epoch 1500: 0.104829
Loss at epoch 1600: 0.102352
Loss at epoch 1700: 0.099986
Loss at epoch 1800: 0.097724
Loss at epoch 1900: 0.095559
Loss at epoch 2000: 0.093486


In [25]:
a = tf.nn.softmax(tf.matmul(x_data,W)+b) # hypothesis

print(a)
print(tf.argmax(a,1))
print(tf.argmax(y_data, 1))

tf.Tensor(
[[4.28412896e-08 1.52905763e-04 9.99847054e-01]
 [2.68331642e-04 4.72454242e-02 9.52486217e-01]
 [1.55243055e-10 9.75707844e-02 9.02429163e-01]
 [1.48567132e-08 9.11770821e-01 8.82291645e-02]
 [1.62209973e-01 8.30934942e-01 6.85506640e-03]
 [8.59201550e-02 9.14077699e-01 2.21895039e-06]
 [8.23345542e-01 1.76651359e-01 3.12498173e-06]
 [9.65990007e-01 3.40100117e-02 1.48562425e-08]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
